architecture=111,48,16
activation=sigmoid
hidden_activation=sigmoid
init_method=xavier
last_epochs=5000
last_actual_epochs=297
last_lr=0.01
last_optimizer=adam
last_loss=mse
best_mse=0.000979656
best_epoch=197
interrupted=0
