architecture=114,48,15
activation=sigmoid
hidden_activation=sigmoid
init_method=xavier
last_epochs=5000
last_actual_epochs=1641
last_lr=0.01
last_optimizer=adam
last_loss=mse
best_mse=0.001320845
best_epoch=1541
interrupted=0
