architecture=73,48,13
activation=sigmoid
init_method=xavier
last_optimizer=adam
last_lr=0.01
last_lr_decay=0
last_momentum=0
last_epochs=3000
last_actual_epochs=3000
last_loss=mse
best_mse=0.0092887055
best_epoch=333
interrupted=0
