architecture=111,48,16
activation=sigmoid
hidden_activation=sigmoid
init_method=xavier
last_epochs=5000
last_actual_epochs=1345
last_lr=0.01
last_optimizer=adam
last_loss=mse
best_mse=0.001033347
best_epoch=1245
interrupted=0
